### ISSUE TITLE
[ASK] Store list of object

### ISSUE THREAD

**Issue by muslimdeveloper** [li-yu/DsPreferences#1]
Excuse me, how to store list of object?

**Comment by li-yu** [comment]
Jetpack DataStore support `Int`, `Long`, `Boolean`, `Float`, `Double`, `String`  only, so you can use a custom converter like this [GsonConverter.kt](https://github.com/li-yu/DataStoreExt/blob/main/app/src/main/java/cn/liyuyu/datastoreext/GsonConverter.kt), convert a list of object to json string., then store and restore it.
